apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyRootUser
metadata:
  name: deny-root-user
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["kube-system", "gatekeeper-system"]
