apiVersion: v1
kind: Pod
metadata:
  name: alpine-disallowed
  labels:
    owner: me.agilebank.demo
spec:
  containers:
    - name: alpine
      image: alpine:3.13.7
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      resources:
        limits:
          cpu: "800m"
          memory: "2Gi"
        requests:
          cpu: "400m"
          memory: "1Gi"
