apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyPrivilegedPod
metadata:
  name: deny-privileged-pod
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["kube-system", "gatekeeper-system"]

