apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: pspfsGroup
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  location: "spec.securityContext.fsGroup"
  parameters:
    pathTests:
    - subPath: "spec.securityContext.fsGroup"
      condition: MustNotExist
    assign:
      value: 3000
