apiVersion: constraints.gatekeeper.sh/v1beta1
kind: TrustedReposPod
metadata:
  name: untrusted-repository-pod
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    # excludedNamespaces: ["list", "excluded", "namespaces"]
  parameters:
    repos:
      - "docker.io/"
